name: 🐛 | Bug 提交
description: 🎤 | 提交你发现的MSS 3中的Bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: Prefeedback
    attributes:
      label: 欢迎你来填写Bug反馈, 是否确认你所反馈的Bug没有人反馈过!
      options:
        - label: 我确认!
          required: true
  - type: dropdown
    id: OS_Name
    attributes:
      label: 系统名称
      description: 你搭建MSS 3的系统名称
      multiple: false
      options:
        - Windows
        - Linux
        - MacOS
    validations:
       required: true
  - type: input
    id: MSS3_Verison
    attributes:
      label: 请写下你发现Bug的MSS 3版本
      placeholder: vx.x.x
    validations:
      required: true
  - type: input
    id: BugInMSS3_Place
    attributes:
      label: 请简述你遇到的问题
      description: 请简要描述你在MSS 3中的什么地方发现了这个Bug
    validations:
      required: true
  - type: textarea
    id: BugInMSS3_Retry
    attributes:
      label: 请简述Bug触发流程
      description: 请简要复述如何MSS 3中触发这个Bug
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: UploadLog
    attributes:
      label: 在此处放置MSS 3日志
      description: MSS 3日志文件存储在\logs, 可以复制到文本框也可以直接上传文件
    validations:
      required: true