name: 🐛 | Bug Report
description: 🎤 | Submit bugs in XXX that you found
title: "[漏洞]: "
labels: ["漏洞"]
body:
- type: markdown
  attributes:
    value: "# 🎁 | You are welcome to fill in the XXX bug feedback!"
- type: checkboxes
  id: Prefeedback
  attributes:
    label: Are you sure that the bug you found is unique
    description: You can search past issue at [here](https://github.com/XXX/issues?q=is%3Aissue)
    options:
      - label: Confirm
        required: true
- type: dropdown
  id: OS_Name
  attributes:
    label: Operating system
    description: The operating system you used for XXX
    multiple: true
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: input
  id: XXX_Verison
  attributes:
    label: Write down the version of XXX where you found the bug
    placeholder: vx.x.x
  validations:
    required: true
- type: input
  id: BugInXXX_Place
  attributes:
    label: Briefly describe the Bug you are experiencing
    description: Please briefly describe where you found this bug in XXX
  validations:
    required: true
- type: textarea
  id: BugInXXX_Retry
  attributes:
    label: Briefly describe the bug triggering process
    description: Please briefly repeat how this bug was triggered in XXX
    placeholder: |
      1. xxx
      2. xxx
      3. xxx
  validations:
    required: true
- type: textarea
  id: UploadLog
  attributes:
    label: Upload XXX logs
    description: XXX log files are stored in \XXX and can be copied to the text box or uploaded directly
  validations:
    required: true
- type: markdown
  attributes:
    value: "### 🎉 | Thank you for your support of XXX!"